// Generated by CoffeeScript 1.8.0
(function() {
  var Cat, CatModel, MyDatabase, Sonrai, test,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Sonrai = require('../sonrai-bundle');

  test = require('tape');

  MyDatabase = new Sonrai.Databases.InMemory();

  CatModel = (function(_super) {
    __extends(CatModel, _super);

    function CatModel() {
      return CatModel.__super__.constructor.apply(this, arguments);
    }

    CatModel.prototype.fields = {
      name: Sonrai.Fields.StringField(),
      gender: Sonrai.Fields.StringField(),
      birthday: Sonrai.Fields.DateTimeField({
        "default": function() {
          return new Date();
        }
      })
    };

    return CatModel;

  })(Sonrai.Model);

  Cat = MyDatabase.register(CatModel);

  test('General tests', function(t) {
    var obj;
    t.plan(2);
    obj = new Cat({
      name: "George",
      gender: "male"
    });
    return obj.save(function() {
      var q;
      q = Cat.query().filter({
        name: "George"
      });
      q.end(function(results) {
        return t.equal(results[0].get('name'), "George");
      });
      q = Cat.query().exclude({
        name: "George"
      });
      return q.end(function(results) {
        return t.equal(results.length, 0);
      });
    });
  });

}).call(this);
