// Generated by CoffeeScript 1.8.0
(function() {
  var MyDatabase, MyModel, Sonrai, obj, q, t, x, _i,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Sonrai = require('sonrai');

  MyDatabase = new Sonrai.Databases.InMemoryDatabase();

  MyModel = (function(_super) {
    __extends(MyModel, _super);

    function MyModel() {
      return MyModel.__super__.constructor.apply(this, arguments);
    }

    MyModel.db = MyDatabase;

    MyModel.prototype._fields = {
      myField: Sonrai.Fields.NumberField({
        "default": 1
      }),
      dateField: Sonrai.Fields.DateTimeField({
        "default": function() {
          return new Date();
        }
      })
    };

    return MyModel;

  })(Sonrai.Model);

  console.log(MyModel.db);

  console.log(new MyModel().db());

  t = new Date().getTime();

  for (x = _i = 0; _i <= 1000; x = ++_i) {
    obj = new MyModel({
      myField: Sonrai.Utils.rand(100)
    });
    obj.save();
  }

  console.log((new Date().getTime()) - t);

  console.log(obj.serialize());

  t = new Date().getTime();

  q = new Sonrai.Query(MyModel);

  q = q.filter({
    myField: {
      gte: 0,
      lte: 100
    }
  });

  q.run();

  console.log((new Date().getTime()) - t);

}).call(this);
