// Generated by CoffeeScript 1.8.0
(function() {
  var MyDatabase, Sonrai;

  Sonrai = require('../sonrai-bundle');

  MyDatabase = new Sonrai.Databases.InMemory();

  require('./test')(MyDatabase);

}).call(this);
